// Probes for Store app launch targets (#219), run against the real AppIds source.
// Exit code 0 = all pass.
using Plinth.App;

var failures = 0;
void Check(string name, bool ok, string? detail = null)
{
    Console.WriteLine($"  {(ok ? "PASS" : "FAIL")} {name}{(detail is null ? "" : " - " + detail)}");
    if (!ok) failures++;
}

// ---- I1 · the ids AppsFolder really reports are accepted --------------------------------
foreach (var id in new[]
{
    "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App",
    "Microsoft.WindowsTerminal_8wekyb3d8bbwe!App",
    "SpotifyAB.SpotifyMusic_zpdnekdrzrea0!Spotify",
    "Chrome",
    "Microsoft.Office.WINWORD.EXE.15",
    "Microsoft.AutoGenerated.{923DD477-5846-686B-A659-0FCCD73851A8}",
    "com.squirrel.slack.slack",
})
    Check($"I1 app id accepted: {id}", AppIds.IsAppId(id));

// ---- I2 · paths, URLs and anything that could split an argument are not ----------------
var notIds = new (string Label, string? Value)[]
{
    ("null", null),
    ("empty", ""),
    ("drive path", @"C:\Program Files\App\app.exe"),
    ("known-folder path", @"{6D809377-6AF0-444B-8957-A3773F02200E}\Notepad++\notepad++.exe"),
    ("UNC path", @"\\server\share\app.exe"),
    ("forward-slash path", "tools/app.exe"),
    ("URL", "steam://rungameid/570"),
    ("space", "Some App"),
    ("tab", "Some\tApp"),
    ("quote", "App\"x"),
    ("newline", "App\nx"),
    ("two bangs", "Family_abc!App!More"),
    ("leading bang", "!App"),
    ("trailing bang", "Family_abc!"),
    ("no letter", "12345.678"),
    ("dots only", ".."),
    ("percent", "%WINDIR%"),
    ("switch", "/select,x"),
    ("too long", new string('a', AppIds.MaxLength + 1)),
};
foreach (var (label, value) in notIds)
    Check($"I2 refused: {label}", !AppIds.IsAppId(value));
Check("I2 the length cap is inclusive", AppIds.IsAppId(new string('a', AppIds.MaxLength)));

// ---- I3 · a target names an id only behind the exact prefix -----------------------------
const string Calc = "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App";
Check("I3 prefix + id parses", AppIds.TryParseTarget(@"shell:AppsFolder\" + Calc, out var parsed) && parsed == Calc, parsed);
Check("I3 prefix case does not matter", AppIds.TryParseTarget(@"SHELL:appsfolder\" + Calc, out parsed) && parsed == Calc, parsed);
Check("I3 ToTarget round-trips", AppIds.TryParseTarget(AppIds.ToTarget(Calc), out parsed) && parsed == Calc, parsed);
foreach (var (label, target) in new (string, string?)[]
{
    ("null", null),
    ("plain path", @"C:\Windows\notepad.exe"),
    ("shortcut", @"C:\ProgramData\Microsoft\Windows\Start Menu\Programs\App.lnk"),
    ("bare id", Calc),
    ("forward slash", "shell:AppsFolder/" + Calc),
    ("other shell folder", @"shell:Startup\" + Calc),
    ("prefix only", @"shell:AppsFolder\"),
    ("prefix + path", @"shell:AppsFolder\{6D809377-6AF0-444B-8957-A3773F02200E}\x.exe"),
    ("prefix + quoted tail", @"shell:AppsFolder\" + Calc + "\" /x"),
    ("prefix + space", @"shell:AppsFolder\" + Calc + " x"),
})
    Check($"I3 not an id target: {label}", !AppIds.TryParseTarget(target, out _));

// ---- I4 · how a target starts -------------------------------------------------------
const string WinDir = @"C:\Windows";
var store = AppIds.LaunchInfo(@"shell:AppsFolder\" + Calc, WinDir);
Check("I4 an id starts the Windows directory's explorer", store.FileName == Path.Combine(WinDir, "explorer.exe"), store.FileName);
Check("I4 ...not through the shell", !store.UseShellExecute);
Check("I4 ...with the target as its one argument",
    store.ArgumentList.Count == 1 && store.ArgumentList[0] == @"shell:AppsFolder\" + Calc,
    string.Join(" | ", store.ArgumentList));
Check("I4 ...and no raw argument string", store.Arguments == "", store.Arguments);
foreach (var target in new[]
{
    @"C:\Windows\notepad.exe",
    @"C:\ProgramData\Microsoft\Windows\Start Menu\Programs\App.lnk",
    @"shell:AppsFolder\" + Calc + "\" /x",
    @"D:\Media",
})
{
    var info = AppIds.LaunchInfo(target, WinDir);
    Check($"I4 anything else starts as before: {target}",
        info.UseShellExecute && info.FileName == target && info.ArgumentList.Count == 0 && info.Arguments == "");
}

// ---- I5 · which AppsFolder entries join the list ----------------------------------------
var folder = new List<(string Name, string Path)>
{
    ("Calculator", Calc),
    ("Notepad++", @"{6D809377-6AF0-444B-8957-A3773F02200E}\Notepad++\notepad++.exe"),
    ("Google Chrome", "Chrome"),
    ("Uninstall Thing", "Vendor.Uninstaller_abc!App"),
    ("Terminal", "Microsoft.WindowsTerminal_8wekyb3d8bbwe!App"),
    ("terminal", "Aaa.OtherTerminal_xyz!App"),
    ("  ", "Blank.Name_xyz!App"),
    ("Steam Game", "steam://rungameid/570"),
};
var taken = new HashSet<string>(new[] { "google chrome" }, StringComparer.OrdinalIgnoreCase);
bool Noise(string n) => n.Contains("uninstall", StringComparison.OrdinalIgnoreCase);
var added = AppIds.Additions(folder, taken, Noise, 50, out var cut);
var names = added.Select(a => a.Name).ToList();
Check("I5 a Store app is added", names.Contains("Calculator"));
Check("I5 ...as a launch target that parses back to its id",
    added.First(a => a.Name == "Calculator").Target is var t && AppIds.TryParseTarget(t, out var back) && back == Calc);
Check("I5 a path entry is left to the Start Menu walk", !names.Contains("Notepad++"));
Check("I5 a URL entry is left out", !names.Contains("Steam Game"));
Check("I5 a name the Start Menu already has keeps its shortcut", !names.Contains("Google Chrome"));
Check("I5 noise is filtered the same way", !names.Contains("Uninstall Thing"));
Check("I5 a blank name is left out", added.All(a => a.Name.Trim().Length > 0));
Check("I5 same-named ids: one kept, the first by id",
    added.Count(a => a.Name.Equals("terminal", StringComparison.OrdinalIgnoreCase)) == 1
    && added.Single(a => a.Name.Equals("terminal", StringComparison.OrdinalIgnoreCase)).Target == AppIds.ToTarget("Aaa.OtherTerminal_xyz!App"),
    string.Join(", ", added));
Check("I5 ...whatever order the folder listed them in",
    AppIds.Additions(Enumerable.Reverse(folder), new HashSet<string>(StringComparer.OrdinalIgnoreCase), Noise, 50, out _)
        .Single(a => a.Name.Equals("terminal", StringComparison.OrdinalIgnoreCase)).Target == AppIds.ToTarget("Aaa.OtherTerminal_xyz!App"));
Check("I5 added names are now taken", taken.Contains("Calculator"));
Check("I5 no cut when there is room", !cut);

var small = AppIds.Additions(folder, new HashSet<string>(StringComparer.OrdinalIgnoreCase), Noise, 1, out var smallCut);
Check("I5 room is a hard cap", small.Count == 1, small.Count.ToString());
Check("I5 ...and running out of it is reported", smallCut);
var none = AppIds.Additions(folder, new HashSet<string>(StringComparer.OrdinalIgnoreCase), Noise, 0, out var noneCut);
Check("I5 no room adds nothing and says so", none.Count == 0 && noneCut);
var exact = AppIds.Additions(new[] { ("Calculator", Calc) }, new HashSet<string>(StringComparer.OrdinalIgnoreCase), Noise, 1, out var exactCut);
Check("I5 exactly enough room is not a cut", exact.Count == 1 && !exactCut);

// ---- I6 · the launch path uses it ---------------------------------------------------------
// Text, and says so: DeckAction needs Windows to run. Without this, deleting the call leaves
// every check above green while a picked Store app hands "shell:AppsFolder\…" to the old
// path again.
var root = AppContext.BaseDirectory;
while (root is not null && !File.Exists(Path.Combine(root, "src", "Plinth", "App", "DeckAction.cs")))
    root = Path.GetDirectoryName(root);
var deck = root is null ? "" : File.ReadAllText(Path.Combine(root, "src", "Plinth", "App", "DeckAction.cs"));
var launchCase = deck.IndexOf("case \"launch\":", StringComparison.Ordinal);
var nextCase = launchCase < 0 ? -1 : deck.IndexOf("case \"", launchCase + 1, StringComparison.Ordinal);
var body = launchCase < 0 || nextCase < 0 ? "" : deck[launchCase..nextCase];
Check("I6 DeckAction's launch starts through AppIds.LaunchInfo", body.Contains("Process.Start(AppIds.LaunchInfo(", StringComparison.Ordinal));
Check("I6 ...and nowhere else in that case", body.Split("Process.Start(").Length == 2);

Console.WriteLine(failures == 0 ? "All app id probes passed." : $"{failures} app id probe(s) FAILED.");
return failures == 0 ? 0 : 1;
