using System.Diagnostics;

namespace Plinth.App;

/// <summary>
/// Store (packaged) applications, named by their AppUserModelId (#219).
///
/// <para>A packaged app has no file a launcher can point at: it lives in the AppsFolder
/// namespace and is started by its id, <c>explorer.exe shell:AppsFolder\&lt;id&gt;</c>. So a
/// launch target that names one is <c>shell:AppsFolder\</c> followed by the id, which is
/// also what the Run dialog accepts, so a saved target can be checked by hand.</para>
///
/// <para>Everything here is a decision over strings, kept apart from the COM enumeration
/// and the process start so a probe can drive it off Windows (tools/AppIds).</para>
/// </summary>
internal static class AppIds
{
    public const string TargetPrefix = @"shell:AppsFolder\";

    /// <summary>Package family names and app ids are each capped at 64 characters by the
    /// package schema; desktop ids at 128. This leaves room for both and refuses the rest.</summary>
    public const int MaxLength = 256;

    /// <summary>True when an AppsFolder item's Path is an application id rather than a
    /// file-system path. Packaged apps report <c>Family_hash!App</c>; desktop programs
    /// that set an id report it (<c>Chrome</c>, <c>Microsoft.AutoGenerated.{GUID}</c>);
    /// everything else reports a path (<c>C:\…</c>, <c>{known-folder}\…\app.exe</c>) or a
    /// URL, and those are the Start Menu walk's business, not this list's.
    ///
    /// <para>An allow-list, because the id ends up as a process argument: no whitespace,
    /// quotes, separators or colons, so it cannot split, escape, or name a path.</para></summary>
    public static bool IsAppId(string? value)
    {
        if (string.IsNullOrEmpty(value) || value.Length > MaxLength)
            return false;
        var letters = 0;
        var bangs = 0;
        foreach (var c in value)
        {
            if (c is >= 'a' and <= 'z' or >= 'A' and <= 'Z') { letters++; continue; }
            if (c is >= '0' and <= '9' or '.' or '_' or '-' or '+' or '{' or '}') continue;
            if (c == '!') { bangs++; continue; }
            return false;
        }
        return letters > 0 && bangs <= 1 && value[0] != '!' && value[^1] != '!';
    }

    public static string ToTarget(string id) => TargetPrefix + id;

    /// <summary>The id a launch target names, when it names one. The prefix is matched
    /// without regard to case, as Windows does.</summary>
    public static bool TryParseTarget(string? target, out string id)
    {
        id = "";
        if (target is null || !target.StartsWith(TargetPrefix, StringComparison.OrdinalIgnoreCase))
            return false;
        var rest = target[TargetPrefix.Length..];
        if (!IsAppId(rest))
            return false;
        id = rest;
        return true;
    }

    /// <summary>How a launch target is started. An app id goes to the Windows directory's
    /// own explorer.exe as a single argument — a full path, so a same-named program earlier
    /// on PATH is not the one that runs. Anything else keeps the shell-execute start every
    /// launch path in this app has always used.</summary>
    public static ProcessStartInfo LaunchInfo(string target, string windowsDir)
    {
        if (!TryParseTarget(target, out var id))
            return new ProcessStartInfo(target) { UseShellExecute = true };
        var info = new ProcessStartInfo(Path.Combine(windowsDir, "explorer.exe")) { UseShellExecute = false };
        info.ArgumentList.Add(ToTarget(id));
        return info;
    }

    /// <summary>Which AppsFolder entries join the picker list. Only application ids; not a
    /// name already taken (the Start Menu's shortcut wins a tie, because it carries the
    /// arguments and working directory the app was installed with); not noise; the first
    /// of two same-named ids by id order, so the choice does not move between runs.</summary>
    /// <param name="taken">Names already listed, compared without case. Updated.</param>
    /// <param name="room">How many more the caller can take.</param>
    /// <param name="truncated">True when <paramref name="room"/> ran out.</param>
    public static List<(string Name, string Target)> Additions(
        IEnumerable<(string Name, string Path)> folder, ISet<string> taken,
        Func<string, bool> isNoise, int room, out bool truncated)
    {
        truncated = false;
        var added = new List<(string, string)>();
        foreach (var (rawName, path) in folder.OrderBy(e => e.Path, StringComparer.OrdinalIgnoreCase))
        {
            var name = rawName?.Trim();
            if (string.IsNullOrEmpty(name) || !IsAppId(path) || isNoise(name) || taken.Contains(name))
                continue;
            if (added.Count >= room)
            {
                truncated = true;
                break;
            }
            taken.Add(name);
            added.Add((name, ToTarget(path)));
        }
        return added;
    }
}
